# Generated by Django 2.1.7 on 2019-02-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190215_1507'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['author']},
        ),
    ]
